# Lesson 1: Advanced RAG Pipeline

In [1]:
import utils

import os
import openai
openai.api_key = utils.get_openai_api_key()

✅ In Answer Relevance, input prompt will be set to __record__.main_input or `Select.RecordInput` .
✅ In Answer Relevance, input response will be set to __record__.main_output or `Select.RecordOutput` .
✅ In Context Relevance, input prompt will be set to __record__.main_input or `Select.RecordInput` .
✅ In Context Relevance, input response will be set to __record__.app.query.rets.source_nodes[:].node.text .
✅ In Groundedness, input source will be set to __record__.app.query.rets.source_nodes[:].node.text .
✅ In Groundedness, input statement will be set to __record__.main_output or `Select.RecordOutput` .

In [2]:
from llama_index import SimpleDirectoryReader

documents = SimpleDirectoryReader(
    input_files=["./eBook-How-to-Build-a-Career-in-AI.pdf"]
).load_data()

In [3]:
print(type(documents), "\n")
print(len(documents), "\n")
print(type(documents[0]))
print(documents[0])

<class 'list'>

41

<class 'llama_index.schema.Document'>
Doc ID: 49467d7d-6e9d-4db2-9848-eba3023d6796
Text: PAGE 1Founder, DeepLearning.AICollected Insights from Andrew Ng
How to  Build Your Career in AIA Simple Guide

## Basic RAG pipeline

In [4]:
from llama_index import Document

document = Document(text="\n\n".join([doc.text for doc in documents]))

In [5]:
from llama_index import VectorStoreIndex
from llama_index import ServiceContext
from llama_index.llms import OpenAI

llm = OpenAI(model="gpt-3.5-turbo", temperature=0.1)
service_context = ServiceContext.from_defaults(
    llm=llm, embed_model="local:BAAI/bge-small-en-v1.5"
)
index = VectorStoreIndex.from_documents([document],
                                        service_context=service_context)

config.json:   0%|          | 0.00/743 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/133M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

[nltk_data] Downloading package punkt to /tmp/llama_index...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [6]:
query_engine = index.as_query_engine()

In [ ]:
print(query_engine)

In [7]:
response = query_engine.query(
    "What are steps to take when finding projects to build your experience?"
)
print(str(response))

Develop a side hustle, ensure the project will help you grow technically, collaborate with good teammates, and consider if the project can be a stepping stone to larger projects.

## Evaluation setup using TruLens

In [8]:
eval_questions = []
with open('eval_questions.txt', 'r') as file:
    for line in file:
        # Remove newline character and convert to integer
        item = line.strip()
        print(item)
        eval_questions.append(item)

What are the keys to building a career in AI?
How can teamwork contribute to success in AI?
What is the importance of networking in AI?
What are some good habits to develop for a successful career?
How can altruism be beneficial in building a career?
What is imposter syndrome and how does it relate to AI?
Who are some accomplished individuals who have experienced imposter syndrome?
What is the first step to becoming good at AI?
What are some common challenges in AI?
Is it normal to find parts of AI challenging?

In [9]:
# You can try your own question:
new_question = "What is the right AI job for me?"
eval_questions.append(new_question)

In [10]:
print(eval_questions)

['What are the keys to building a career in AI?', 'How can teamwork contribute to success in AI?', 'What is the importance of networking in AI?', 'What are some good habits to develop for a successful career?', 'How can altruism be beneficial in building a career?', 'What is imposter syndrome and how does it relate to AI?', 'Who are some accomplished individuals who have experienced imposter syndrome?', 'What is the first step to becoming good at AI?', 'What are some common challenges in AI?', 'Is it normal to find parts of AI challenging?', 'What is the right AI job for me?']

In [11]:
from trulens_eval import Tru
tru = Tru()

tru.reset_database()

🦑 Tru initialized with db url sqlite:///default.sqlite .
🛑 Secret keys may be written to the database. See the `database_redact_keys` option of `Tru` to prevent this.

For the classroom, we've written some of the code in helper functions inside a utils.py file.  
- You can view the utils.py file in the file directory by clicking on the "Jupyter" logo at the top of the notebook.
- In later lessons, you'll get to work directly with the code that's currently wrapped inside these helper functions, to give you more options to customize your RAG pipeline.

In [12]:
from utils import get_prebuilt_trulens_recorder

tru_recorder = get_prebuilt_trulens_recorder(query_engine,
                                             app_id="Direct Query Engine")

In [13]:
with tru_recorder as recording:
    for question in eval_questions:
        response = query_engine.query(question)

In [14]:
records, feedback = tru.get_records_and_feedback(app_ids=[])

In [15]:
records.head()

,app_id,app_json,type,record_id,input,output,tags,record_json,cost_json,perf_json,ts,Answer Relevance,Context Relevance,Groundedness,Answer Relevance_calls,Context Relevance_calls,Groundedness_calls,latency,total_tokens,total_cost
0,Direct Query Engine,"{""app_id"": ""Direct Query Engine"", ""tags"": ""-"",...",RetrieverQueryEngine(llama_index.query_engine....,record_hash_d42ad2c9d57b28918036dc486539b554,"""What are the keys to building a career in AI?""","""Learning foundational technical skills, worki...",-,"{""record_id"": ""record_hash_d42ad2c9d57b2891803...","{""n_requests"": 1, ""n_successful_requests"": 1, ...","{""start_time"": ""2026-06-14T17:24:42.029926"", ""...",2026-06-14T17:24:43.262982,1.0,1.00,1.000000,[{'args': {'prompt': 'What are the keys to bui...,[{'args': {'prompt': 'What are the keys to bui...,"[{'args': {'source': 'PAGE 1Founder, DeepLearn...",1,2107,0.003206
1,Direct Query Engine,"{""app_id"": ""Direct Query Engine"", ""tags"": ""-"",...",RetrieverQueryEngine(llama_index.query_engine....,record_hash_c05674a5ed2c9c90e22f5672e73e9dd2,"""How can teamwork contribute to success in AI?""","""Teamwork can contribute to success in AI by a...",-,"{""record_id"": ""record_hash_c05674a5ed2c9c90e22...","{""n_requests"": 1, ""n_successful_requests"": 1, ...","{""start_time"": ""2026-06-14T17:24:43.389801"", ""...",2026-06-14T17:24:44.446215,1.0,0.55,1.000000,[{'args': {'prompt': 'How can teamwork contrib...,[{'args': {'prompt': 'How can teamwork contrib...,[{'args': {'source': 'Hopefully the previous c...,1,1679,0.002546
2,Direct Query Engine,"{""app_id"": ""Direct Query Engine"", ""tags"": ""-"",...",RetrieverQueryEngine(llama_index.query_engine....,record_hash_4c279032cca2eec423348680f569451a,"""What is the importance of networking in AI?""","""Networking is crucial in AI as it helps indiv...",-,"{""record_id"": ""record_hash_4c279032cca2eec4233...","{""n_requests"": 1, ""n_successful_requests"": 1, ...","{""start_time"": ""2026-06-14T17:24:44.563480"", ""...",2026-06-14T17:24:45.752201,1.0,0.55,0.666667,[{'args': {'prompt': 'What is the importance o...,[{'args': {'prompt': 'What is the importance o...,[{'args': {'source': 'Hopefully the previous c...,1,1694,0.002576
3,Direct Query Engine,"{""app_id"": ""Direct Query Engine"", ""tags"": ""-"",...",RetrieverQueryEngine(llama_index.query_engine....,record_hash_b84f101e04165aabc0d40be329e358ec,"""What are some good habits to develop for a su...","""Developing good habits in areas such as eatin...",-,"{""record_id"": ""record_hash_b84f101e04165aabc0d...","{""n_requests"": 1, ""n_successful_requests"": 1, ...","{""start_time"": ""2026-06-14T17:24:45.866320"", ""...",2026-06-14T17:24:47.359465,1.0,0.95,NaN,[{'args': {'prompt': 'What are some good habit...,[{'args': {'prompt': 'What are some good habit...,NaN,1,1631,0.002465
4,Direct Query Engine,"{""app_id"": ""Direct Query Engine"", ""tags"": ""-"",...",RetrieverQueryEngine(llama_index.query_engine....,record_hash_85b2b8d0bf2a45886cc5bb0ae4a7e040,"""How can altruism be beneficial in building a ...","""Helping others during the journey of building...",-,"{""record_id"": ""record_hash_85b2b8d0bf2a45886cc...","{""n_requests"": 1, ""n_successful_requests"": 1, ...","{""start_time"": ""2026-06-14T17:24:47.486653"", ""...",2026-06-14T17:24:48.271016,1.0,NaN,NaN,[{'args': {'prompt': 'How can altruism be bene...,NaN,NaN,0,1612,0.002427

In [16]:
# launches on http://localhost:8501/
tru.run_dashboard()

Starting dashboard ...
Config file already exists. Skipping writing process.
Credentials file already exists. Skipping writing process.

Accordion(children=(VBox(children=(VBox(children=(Label(value='STDOUT'), Output())), VBox(children=(Label(valu…

Dashboard started at https://s172-29-20-242p38560.lab-aws-production.deeplearning.ai/ .

## Advanced RAG pipeline

### 1. Sentence Window retrieval

In [17]:
from llama_index.llms import OpenAI

llm = OpenAI(model="gpt-3.5-turbo", temperature=0.1)

In [18]:
from utils import build_sentence_window_index

sentence_index = build_sentence_window_index(
    document,
    llm,
    embed_model="local:BAAI/bge-small-en-v1.5",
    save_dir="sentence_index"
)

In [19]:
from utils import get_sentence_window_query_engine

sentence_window_engine = get_sentence_window_query_engine(sentence_index)

config.json:   0%|          | 0.00/799 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/443 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/279 [00:00<?, ?B/s]

In [20]:
window_response = sentence_window_engine.query(
    "how do I get started on a personal project in AI?"
)
print(str(window_response))

To get started on a personal project in AI, you can begin by identifying a project that aligns with your career goals and interests. It's important to choose a project that is responsible, ethical, and beneficial to people. Once you have selected a project, you can follow the steps outlined in the chapters provided, such as scoping the project, executing it with an eye toward career development, and building a portfolio that demonstrates skill progression. By following these guidelines, you can embark on a personal AI project that not only enhances your skills but also makes a positive impact in the field.

In [21]:
tru.reset_database()

tru_recorder_sentence_window = get_prebuilt_trulens_recorder(
    sentence_window_engine,
    app_id = "Sentence Window Query Engine"
)

In [22]:
for question in eval_questions:
    with tru_recorder_sentence_window as recording:
        response = sentence_window_engine.query(question)
        print(question)
        print(str(response))

What are the keys to building a career in AI?
Learning foundational technical skills, working on projects, finding a job, and being part of a supportive community are the keys to building a career in AI.
How can teamwork contribute to success in AI?
Teammates play a crucial role in the success of AI projects. Working collaboratively with colleagues who are dedicated, continuously learning, and focused on using AI to benefit all people can positively influence one's own work ethic and outcomes. The ability to work effectively in a team, leveraging each member's strengths and insights, can lead to improved project outcomes and overall success in the field of AI.
What is the importance of networking in AI?
Networking in AI is crucial as it can provide valuable insights, guidance, and opportunities for individuals looking to advance in the field. By connecting with professionals who have experience in AI, individuals can gain knowledge about the industry, potential career paths, and current trends. Networking also allows individuals to build relationships with others in the field, which can lead to mentorship, collaboration on projects, and even job opportunities. Additionally, networking can help individuals stay updated on the latest developments in AI and expand their professional connections for future career growth.
What are some good habits to develop for a successful career?
Developing good habits in areas such as eating, exercise, sleep, personal relationships, work, learning, and self-care can help individuals move forward in their careers while maintaining their health.
How can altruism be beneficial in building a career?
Helping others and aiming to lift them during one's career journey can lead to better outcomes for oneself.
What is imposter syndrome and how does it relate to AI?
Imposter syndrome is a phenomenon where individuals doubt their accomplishments and have a persistent fear of being exposed as a fraud. In the context of AI, newcomers to the field may experience imposter syndrome, feeling like they do not truly belong in the AI community despite their success. This can be a significant challenge for individuals entering the AI field, as it may hinder their growth and confidence in pursuing a career in artificial intelligence.
Who are some accomplished individuals who have experienced imposter syndrome?
Sheryl Sandberg, Michelle Obama, Tom Hanks, and Mike Cannon-Brookes are some accomplished individuals who have experienced imposter syndrome.
What is the first step to becoming good at AI?
The first step to becoming good at AI is learning foundational technical skills.
What are some common challenges in AI?
Some common challenges in AI include keeping up-to-date with rapidly evolving technologies, the iterative nature of AI projects leading to uncertainties in project management, the need to collaborate with stakeholders who may lack expertise in AI, and the difficulty in finding suitable projects and estimating timelines and returns on investment.
Is it normal to find parts of AI challenging?
It is normal to find parts of AI challenging.
What is the right AI job for me?
The right AI job for you can be found by following the steps outlined in Chapter 9: Finding the Right AI Job for You. It involves building a portfolio of projects that show skill progression, using a simple framework to start your AI job search, and utilizing informational interviews to find the right job that complements your career goals.

In [23]:
tru.get_leaderboard(app_ids=[])

                              Answer Relevance   latency  total_cost
app_id
Sentence Window Query Engine               1.0  1.363636    0.000808

In [24]:
# launches on http://localhost:8501/
tru.run_dashboard()

Starting dashboard ...
Config file already exists. Skipping writing process.
Credentials file already exists. Skipping writing process.
Dashboard already running at path: https://s172-29-20-242p38560.lab-aws-production.deeplearning.ai/

### 2. Auto-merging retrieval

In [25]:
from utils import build_automerging_index

automerging_index = build_automerging_index(
    documents,
    llm,
    embed_model="local:BAAI/bge-small-en-v1.5",
    save_dir="merging_index"
)

In [26]:
from utils import get_automerging_query_engine

automerging_query_engine = get_automerging_query_engine(
    automerging_index,
)

In [27]:
auto_merging_response = automerging_query_engine.query(
    "How do I build a portfolio of AI projects?"
)
print(str(auto_merging_response))

> Merging 1 nodes into parent node.
> Parent node id: cfc9dc64-6a68-46ef-bd53-ef8e68bd0b52.
> Parent node text: PAGE 21Building a Portfolio of
Projects that Shows
Skill Progression CHAPTER 6
PROJECTS

> Merging 1 nodes into parent node.
> Parent node id: 9b09221c-311f-49a3-a01e-196068611279.
> Parent node text: PAGE 21Building a Portfolio of
Projects that Shows
Skill Progression CHAPTER 6
PROJECTS

To build a portfolio of AI projects, it is important to start with simple projects and gradually progress to more complex undertakings. Showing progress over time is beneficial when seeking job opportunities. Additionally, effective communication is key in explaining your thought process to others, showcasing the value of your work, and gaining trust for larger projects.

In [28]:
tru.reset_database()

tru_recorder_automerging = get_prebuilt_trulens_recorder(automerging_query_engine,
                                                         app_id="Automerging Query Engine")

In [ ]:
for question in eval_questions:
    with tru_recorder_automerging as recording:
        response = automerging_query_engine.query(question)
        print(question)
        print(response)

A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f3546c82e60 is calling an instrumented method <function BaseQueryEngine.query at 0x7f36bab3b640>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f35b4250d00) using this function.
A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f3546c82e60 is calling an instrumented method <function RetrieverQueryEngine.retrieve at 0x7f36b5b46a70>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f35b4250d00) using this function.
A new object of type <class 'llama_index.retrievers.auto_merging_retriever.AutoMergingRetriever'> at 0x7f35981acb20 is calling an instrumented method <function BaseRetriever.retrieve at 0x7f36bab3a9e0>. The path of this call may be incorrect.
Guessing path of new object is app.retriever based on other object (0x7f36083a3850) using this function.
A new object of type <class 'llama_index.indices.vector_store.retrievers.retriever.VectorIndexRetriever'> at 0x7f35981acee0 is calling an instrumented method <function BaseRetriever.retrieve at 0x7f36bab3a9e0>. The path of this call may be incorrect.
Guessing path of new object is app.retriever based on other object (0x7f36083a3850) using this function.

> Merging 2 nodes into parent node.
> Parent node id: 8c4472c4-5218-4dab-9d94-348fe8fb3449.
> Parent node text: PAGE 3Table of
ContentsIntroduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to Ca...

> Merging 1 nodes into parent node.
> Parent node id: 3c074cdc-92a8-4285-97c0-405791224304.
> Parent node text: PAGE 3Table of
ContentsIntroduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to Ca...

A new object of type <class 'llama_index.response_synthesizers.compact_and_refine.CompactAndRefine'> at 0x7f3546c82dd0 is calling an instrumented method <function CompactAndRefine.get_response at 0x7f36b9fef520>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer based on other object (0x7f35b4251480) using this function.
A new object of type <class 'llama_index.response_synthesizers.compact_and_refine.CompactAndRefine'> at 0x7f3546c82dd0 is calling an instrumented method <function Refine.get_response at 0x7f36b959b2e0>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer based on other object (0x7f35b4251480) using this function.
A new object of type <class 'llama_index.llm_predictor.base.LLMPredictor'> at 0x7f36618d5600 is calling an instrumented method <function LLMPredictor.predict at 0x7f36c7031120>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer.service_context.llm_predictor based on other object (0x7f3660590d00) using this function.
A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f3546c82e60 is calling an instrumented method <function RetrieverQueryEngine.retrieve at 0x7f36b5b46a70>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f35b4250d00) using this function.

What are the keys to building a career in AI?
The keys to building a career in AI include learning foundational technical skills, working on projects, finding a job, and being part of a community. Additionally, collaborating with others, influencing, and being influenced by others are critical aspects for success in AI.

A new object of type <class 'llama_index.response_synthesizers.compact_and_refine.CompactAndRefine'> at 0x7f3546c82dd0 is calling an instrumented method <function Refine.get_response at 0x7f36b959b2e0>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer based on other object (0x7f35b4251480) using this function.
A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f3546c82e60 is calling an instrumented method <function RetrieverQueryEngine.retrieve at 0x7f36b5b46a70>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f35b4250d00) using this function.

How can teamwork contribute to success in AI?
Teamwork can contribute to success in AI by enabling individuals to work more effectively on large projects. Collaboration within a team allows for a pooling of diverse skills, knowledge, and perspectives, leading to more innovative solutions and better outcomes. Additionally, the ability to work with others, influence them, and be influenced by them is crucial in the field of AI, emphasizing the importance of interpersonal and communication skills in achieving success.
> Merging 3 nodes into parent node.
> Parent node id: 87f60a15-ca32-4c74-a75f-c5b7c7273634.
> Parent node text: PAGE 35Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more comple...

> Merging 1 nodes into parent node.
> Parent node id: 8de86b08-af9d-4ead-b3af-7da66678acab.
> Parent node text: PAGE 35Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more comple...

A new object of type <class 'llama_index.response_synthesizers.compact_and_refine.CompactAndRefine'> at 0x7f3546c82dd0 is calling an instrumented method <function Refine.get_response at 0x7f36b959b2e0>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer based on other object (0x7f35b4251480) using this function.
A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f3546c82e60 is calling an instrumented method <function RetrieverQueryEngine.retrieve at 0x7f36b5b46a70>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f35b4250d00) using this function.

What is the importance of networking in AI?
Networking is crucial in AI as it helps individuals build a strong professional network within the industry. This network can provide support, guidance, and opportunities for career advancement. By connecting with others in the field, individuals can gain valuable insights, access resources, and potentially open doors to new roles or projects.
> Merging 2 nodes into parent node.
> Parent node id: b9b294e8-2865-46ad-83ad-015b14bc432b.
> Parent node text: PAGE 36Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
on...

> Merging 2 nodes into parent node.
> Parent node id: 7289cc8c-873a-484a-8e35-cdb18ac181eb.
> Parent node text: PAGE 11
The Best Way to Build
a New Habit
One of my favorite books is BJ Fogg’s, Tiny Habits: Th...

> Merging 1 nodes into parent node.
> Parent node id: b6dcce97-0fbd-4a3b-8e31-571806bee67d.
> Parent node text: PAGE 36Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
on...

> Merging 1 nodes into parent node.
> Parent node id: a5a87723-3fac-4af1-b5ca-29e04f2054ff.
> Parent node text: PAGE 11
The Best Way to Build
a New Habit
One of my favorite books is BJ Fogg’s, Tiny Habits: Th...

A new object of type <class 'llama_index.response_synthesizers.compact_and_refine.CompactAndRefine'> at 0x7f3546c82dd0 is calling an instrumented method <function Refine.get_response at 0x7f36b959b2e0>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer based on other object (0x7f35b4251480) using this function.
A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f3546c82e60 is calling an instrumented method <function RetrieverQueryEngine.retrieve at 0x7f36b5b46a70>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f35b4250d00) using this function.

What are some good habits to develop for a successful career?
Good habits to develop for a successful career include habits related to eating well, exercising regularly, getting enough sleep, maintaining positive personal relationships, consistently working towards learning and self-improvement, and practicing self-care. These habits can help individuals progress in their careers while also ensuring their overall well-being.
> Merging 2 nodes into parent node.
> Parent node id: a74be5a5-13da-4104-ac5b-305173eba136.
> Parent node text: PAGE 30Finding someone to interview isn’t always easy, but many people who are in senior position...

> Merging 1 nodes into parent node.
> Parent node id: f6fe8828-ce45-4ea9-afa0-37c90c82b69d.
> Parent node text: PAGE 30Finding someone to interview isn’t always easy, but many people who are in senior position...

A new object of type <class 'llama_index.response_synthesizers.compact_and_refine.CompactAndRefine'> at 0x7f3546c82dd0 is calling an instrumented method <function Refine.get_response at 0x7f36b959b2e0>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer based on other object (0x7f35b4251480) using this function.
A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f3546c82e60 is calling an instrumented method <function RetrieverQueryEngine.retrieve at 0x7f36b5b46a70>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f35b4250d00) using this function.

How can altruism be beneficial in building a career?
Altruism can be beneficial in building a career by creating opportunities for networking and mentorship. By helping others and lifting them up during their journey, individuals can establish strong relationships within their industry. This can lead to receiving support and guidance from experienced professionals, as well as potential referrals to job opportunities. Additionally, practicing altruism can enhance one's reputation and credibility in the field, ultimately contributing to long-term career success.
> Merging 5 nodes into parent node.
> Parent node id: 51d3a895-6705-4fae-82c9-80957521e903.
> Parent node text: PAGE 38Before we dive into the final chapter of this book, I’d like to address the serious matter...

> Merging 1 nodes into parent node.
> Parent node id: 79401e5f-65cc-4859-9811-ed22960248bb.
> Parent node text: PAGE 37Overcoming Imposter
SyndromeCHAPTER 11

> Merging 3 nodes into parent node.
> Parent node id: 089b0eb0-d865-4cd3-8a6b-6e0dba455cfe.
> Parent node text: PAGE 39My three-year-old daughter (who can barely count to 12) regularly tries to teach things to...

> Merging 1 nodes into parent node.
> Parent node id: 0b4bfcda-2fc5-4e5f-9fe0-4ed371703656.
> Parent node text: PAGE 38Before we dive into the final chapter of this book, I’d like to address the serious matter...

> Merging 1 nodes into parent node.
> Parent node id: e2d9bd95-69e8-4214-8869-7a14c8f4d5ff.
> Parent node text: PAGE 37Overcoming Imposter
SyndromeCHAPTER 11

> Merging 1 nodes into parent node.
> Parent node id: a8b28adf-932d-42e8-9188-608137fe4575.
> Parent node text: PAGE 39My three-year-old daughter (who can barely count to 12) regularly tries to teach things to...

A new object of type <class 'llama_index.response_synthesizers.compact_and_refine.CompactAndRefine'> at 0x7f3546c82dd0 is calling an instrumented method <function Refine.get_response at 0x7f36b959b2e0>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer based on other object (0x7f35b4251480) using this function.
A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f3546c82e60 is calling an instrumented method <function RetrieverQueryEngine.retrieve at 0x7f36b5b46a70>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f35b4250d00) using this function.

What is imposter syndrome and how does it relate to AI?
Imposter syndrome is when individuals doubt their accomplishments and have a persistent fear of being exposed as a fraud, despite evidence of their competence. In the context of AI, newcomers to the field may experience imposter syndrome due to the technical complexity and the presence of highly capable individuals. It is highlighted that imposter syndrome is common even among accomplished people in the AI community, and the message is to not let it discourage anyone from pursuing growth in AI.
> Merging 3 nodes into parent node.
> Parent node id: 51d3a895-6705-4fae-82c9-80957521e903.
> Parent node text: PAGE 38Before we dive into the final chapter of this book, I’d like to address the serious matter...

> Merging 1 nodes into parent node.
> Parent node id: 79401e5f-65cc-4859-9811-ed22960248bb.
> Parent node text: PAGE 37Overcoming Imposter
SyndromeCHAPTER 11

> Merging 3 nodes into parent node.
> Parent node id: 089b0eb0-d865-4cd3-8a6b-6e0dba455cfe.
> Parent node text: PAGE 39My three-year-old daughter (who can barely count to 12) regularly tries to teach things to...

> Merging 1 nodes into parent node.
> Parent node id: 0b4bfcda-2fc5-4e5f-9fe0-4ed371703656.
> Parent node text: PAGE 38Before we dive into the final chapter of this book, I’d like to address the serious matter...

> Merging 1 nodes into parent node.
> Parent node id: e2d9bd95-69e8-4214-8869-7a14c8f4d5ff.
> Parent node text: PAGE 37Overcoming Imposter
SyndromeCHAPTER 11

> Merging 1 nodes into parent node.
> Parent node id: a8b28adf-932d-42e8-9188-608137fe4575.
> Parent node text: PAGE 39My three-year-old daughter (who can barely count to 12) regularly tries to teach things to...

A new object of type <class 'llama_index.response_synthesizers.compact_and_refine.CompactAndRefine'> at 0x7f3546c82dd0 is calling an instrumented method <function Refine.get_response at 0x7f36b959b2e0>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer based on other object (0x7f35b4251480) using this function.
A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f3546c82e60 is calling an instrumented method <function RetrieverQueryEngine.retrieve at 0x7f36b5b46a70>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f35b4250d00) using this function.

Who are some accomplished individuals who have experienced imposter syndrome?
Sheryl Sandberg, Michelle Obama, Tom Hanks, and Mike Cannon-Brookes are some accomplished individuals who have experienced imposter syndrome.

A new object of type <class 'llama_index.response_synthesizers.compact_and_refine.CompactAndRefine'> at 0x7f3546c82dd0 is calling an instrumented method <function Refine.get_response at 0x7f36b959b2e0>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer based on other object (0x7f35b4251480) using this function.
A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f3546c82e60 is calling an instrumented method <function RetrieverQueryEngine.retrieve at 0x7f36b5b46a70>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f35b4250d00) using this function.

What is the first step to becoming good at AI?
The first step to becoming good at AI is to suck at it.

A new object of type <class 'llama_index.response_synthesizers.compact_and_refine.CompactAndRefine'> at 0x7f3546c82dd0 is calling an instrumented method <function Refine.get_response at 0x7f36b959b2e0>. The path of this call may be incorrect.
Guessing path of new object is app._response_synthesizer based on other object (0x7f35b4251480) using this function.
A new object of type <class 'llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine'> at 0x7f3546c82e60 is calling an instrumented method <function RetrieverQueryEngine.retrieve at 0x7f36b5b46a70>. The path of this call may be incorrect.
Guessing path of new object is app based on other object (0x7f35b4250d00) using this function.

What are some common challenges in AI?
Some common challenges in AI include the highly iterative nature of AI projects, difficulties in project management due to uncertainty in time estimates for achieving target accuracy, and technical challenges that researchers and professionals in the field have faced.
> Merging 3 nodes into parent node.
> Parent node id: 51d3a895-6705-4fae-82c9-80957521e903.
> Parent node text: PAGE 38Before we dive into the final chapter of this book, I’d like to address the serious matter...

> Merging 1 nodes into parent node.
> Parent node id: 0b4bfcda-2fc5-4e5f-9fe0-4ed371703656.
> Parent node text: PAGE 38Before we dive into the final chapter of this book, I’d like to address the serious matter...

In [33]:
tru.get_leaderboard(app_ids=[])

,Groundedness,Context Relevance,Answer Relevance,latency,total_cost
app_id,,,,,
Automerging Query Engine,0.810606,0.713636,0.990909,2.363636,0.000868

In [ ]:
# launches on http://localhost:8501/
tru.run_dashboard()